server:
  port: 8081

spring:
  application:
    name: iot-simulator-service
  rabbitmq:
    host: localhost
    port: 5672
    username: mepsan_mq
    password: mepsan123

simulator:
  station-count: 50        # Sabit havuzdaki istasyon sayısı
  sales-rate-ms: 1000      # 1 saniyede bir satış
  telemetry-rate-ms: 2000  # 2 saniyede bir telemetri
  refill-rate-ms: 60000
  base-price: 42.10